version: 2

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 10
    groups:
      dev-eslint-related:
        dependency-type: 'development'
        patterns:
          - 'eslint'
          - 'eslint*'
          - '@eslint/*'
          - '@types/eslint__js'
          - 'typescript'
          - 'typescript-eslint'

      dev:
        dependency-type: 'development'
        patterns:
          - '@commitlint/*'
          - '@marcalexiei/prettier-config'
          - 'husky'
          - 'prettier'
