packages:
  - ./packages/**
  - ./tests/**

# esbuild is used internally by Vitest, but Vitest itself is not run in this repository.
# We only need to test spec files using eslint.
ignoredBuiltDependencies:
  - esbuild

onlyBuiltDependencies:
  - unrs-resolver
