name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {}

env:
  HUSKY: 0
  CI: true

jobs:
  test:
    name: Test (Node ${{ matrix.node }})

    permissions:
      contents: read

    runs-on: ubuntu-latest
    timeout-minutes: 5

    strategy:
      fail-fast: true
      matrix:
        node:
          - 20
          - 22
          - 24

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-version: ${{ matrix.node }}

      - name: Run build
        run: pnpm run build

      - name: Run test
        run: pnpm run test

  code-checks:
    name: Code checks

    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Typecheck
        run: pnpm run typecheck

      - name: Lint
        run: pnpm run lint

      - name: Format
        run: pnpm run format

  ci-ok:
    name: CI OK
    if: always()
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs:
      - test
      - code-checks
    steps:
      - name: Exit with error if some jobs are not successful
        run: exit 1
        if: ${{ always() && (contains(needs.*.result, 'failure') || contains(needs.*.result, 'skipped') || contains(needs.*.result, 'cancelled')) }}
